[opener]
tmux_session = [
    { run = 'bash ~/.local/bin/tmux-sessionizer.sh "$1"', desc = "Tmux Session" }
]

[open]
prepend_rules = [
    { url = "*/", use = [ "open", "tmux_session", "edit", "reveal" ] }
]
